export const OLD_TESTAMENT = [
    { id: 'gen', name: '창세기', chapters: 50 },
    { id: 'exo', name: '출애굽기', chapters: 40 },
    { id: 'lev', name: '레위기', chapters: 27 },
    { id: 'num', name: '민수기', chapters: 36 },
    { id: 'deut', name: '신명기', chapters: 34 },
    { id: 'jos', name: '여호수아', chapters: 24 },
    { id: 'jdg', name: '사사기', chapters: 21 },
    { id: 'rth', name: '룻기', chapters: 4 },
    { id: '1sam', name: '사무엘상', chapters: 31 },
    { id: '2sam', name: '사무엘하', chapters: 24 },
    { id: '1kgs', name: '열왕기상', chapters: 22 },
    { id: '2kgs', name: '열왕기하', chapters: 25 },
    { id: '1chr', name: '역대상', chapters: 29 },
    { id: '2chr', name: '역대하', chapters: 36 },
    { id: 'ezr', name: '에스라', chapters: 10 },
    { id: 'neh', name: '느헤미야', chapters: 13 },
    { id: 'esth', name: '에스더', chapters: 10 },
    { id: 'job', name: '욥기', chapters: 42 },
    { id: 'psm', name: '시편', chapters: 150 },
    { id: 'prv', name: '잠언', chapters: 31 },
    { id: 'ecc', name: '전도서', chapters: 12 },
    { id: 'song', name: '아가', chapters: 8 },
    { id: 'isa', name: '이사야', chapters: 66 },
    { id: 'jer', name: '예레미야', chapters: 52 },
    { id: 'lam', name: '예레미야애가', chapters: 5 },
    { id: 'ezk', name: '에스겔', chapters: 48 },
    { id: 'dan', name: '다니엘', chapters: 12 },
    { id: 'hos', name: '호세아', chapters: 14 },
    { id: 'joel', name: '요엘', chapters: 3 },
    { id: 'amos', name: '아모스', chapters: 9 },
    { id: 'obad', name: '오바댜', chapters: 1 },
    { id: 'jon', name: '요나', chapters: 4 },
    { id: 'mic', name: '미가', chapters: 7 },
    { id: 'nah', name: '나훔', chapters: 3 },
    { id: 'hab', name: '하박국', chapters: 3 },
    { id: 'zep', name: '스바냐', chapters: 3 },
    { id: 'hag', name: '학개', chapters: 2 },
    { id: 'zec', name: '스가랴', chapters: 14 },
    { id: 'mal', name: '말라기', chapters: 4 }
];

export const NEW_TESTAMENT = [
    { id: 'mat', name: '마태복음', chapters: 28 },
    { id: 'mrk', name: '마가복음', chapters: 16 },
    { id: 'luk', name: '누가복음', chapters: 24 },
    { id: 'john', name: '요한복음', chapters: 21 },
    { id: 'acts', name: '사도행전', chapters: 28 },
    { id: 'rom', name: '로마서', chapters: 16 },
    { id: '1cor', name: '고린도전서', chapters: 16 },
    { id: '2cor', name: '고린도후서', chapters: 13 },
    { id: 'gal', name: '갈라디아서', chapters: 6 },
    { id: 'eph', name: '에베소서', chapters: 6 },
    { id: 'phil', name: '빌립보서', chapters: 4 },
    { id: 'col', name: '골로새서', chapters: 4 },
    { id: '1the', name: '데살로니가전서', chapters: 5 },
    { id: '2the', name: '데살로니가후서', chapters: 3 },
    { id: '1tim', name: '디모데전서', chapters: 6 },
    { id: '2tim', name: '디모데후서', chapters: 4 },
    { id: 'tit', name: '디도서', chapters: 3 },
    { id: 'phm', name: '빌레몬서', chapters: 1 },
    { id: 'heb', name: '히브리서', chapters: 13 },
    { id: 'jas', name: '야고보서', chapters: 5 },
    { id: '1pet', name: '베드로전서', chapters: 5 },
    { id: '2pet', name: '베드로후서', chapters: 3 },
    { id: '1jn', name: '요한일서', chapters: 5 },
    { id: '2jn', name: '요한이서', chapters: 1 },
    { id: '3jn', name: '요한삼서', chapters: 1 },
    { id: 'jud', name: '유다서', chapters: 1 },
    { id: 'rev', name: '요한계시록', chapters: 22 }
];

export const ALL_BOOKS = [...OLD_TESTAMENT, ...NEW_TESTAMENT];

export const VERSIONS = [
    { id: 'rnksv', name: '새번역' },
    { id: 'krv', name: '개역개정' }
];
